services:
  - type: web
    name: traffic-violation-system
    env: python
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn CAPSTONE_PROJECT.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: CAPSTONE_PROJECT.render_media_settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: ".onrender.com"
      - key: PYTHON_VERSION
        value: "3.10.0"
      - key: DATABASE_URL
        fromDatabase:
          name: traffic_violation_db
          property: connectionString
      - key: RENDER
        value: "True"
      - key: MEDIA_URL
        value: "/media/"
      - key: RECAPTCHA_SITE_KEY
        value: "6LdPGjUrAAAAAIwQo_5ZnIW_lSEWqB16xK3lm5PG"
      - key: RECAPTCHA_SECRET_KEY
        value: "6LdPGjUrAAAAAIg7w66Wu6ejYHT4K4Vp0YoqSN56"
    disk:
      name: media
      mountPath: /opt/render/project/src/media
      sizeGB: 10
      
databases:
  - name: traffic_violation_db
    databaseName: traffic_violation_db
    plan: free
    ipAllowList: [] 